### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Cologler** [yinyue200/OpenCC.UWP#1]
全新的项目，从 nuget 下载的 package，无结果：

![snipaste_2018-01-30_19-19-01](https://user-images.githubusercontent.com/10906962/35563685-7eef170c-05f2-11e8-86a9-0331fe4fa6d4.png)

**Comment by Cologler** [comment]
看了下单元测试，原来还有 `Error()` 这个 API……

返回的错误信息是：opencc/s2t.json not found or not accessible.

**Comment by Cologler** [comment]
不能把数据文件打包进 nuget package 吗？

**Comment by yinyue200** [comment]
@Cologler 你解决了？

**Comment by Cologler** [comment]
@yinyue200 我把 opencc 这个目录丢进 build 后的 appx 目录就能跑了。缺点是每次构建都要丢一遍（当然也可以写 build script）。

不过上述可以整合到 nuget package 包里面才对……
你要不要把 .nuspec 丢进 repo 里面？

**Comment by yinyue200** [comment]
@Cologler 主要是里面的东西其实就是词库，我这里又没有维护，还是丢给用户维护好。。。。不用丢到build后的文件夹，你直接加到VS里面把build方式改成内容就行
